"""Framework-independent security primitives for the Python sidecar."""

from .auth import (
    AUTHORIZATION_HEADER,
    LEGACY_AUTH_HEADER,
    AuthManager,
    constant_time_token_equal,
    parse_bearer_token,
)
from .body_limit import BodyLimitMiddleware, BodySizeLimitMiddleware
from .errors import (
    AuthenticationError,
    AuthenticationUnavailableError,
    OutboundPolicyError,
    OutboundResolutionError,
    PairingAttemptsExceededError,
    PairingError,
    PairingExpiredError,
    PairingInvalidError,
    PairingReplayError,
    PairingUnavailableError,
    PathNotFoundSecurityError,
    RequestBodyError,
    RequestBodyTooLargeError,
    SecurityError,
    UnsafePathError,
)
from .outbound import (
    SENSITIVE_REDIRECT_HEADERS,
    OutboundMode,
    OutboundPolicy,
    ValidatedURL,
    same_origin,
    strip_sensitive_headers_on_cross_origin,
    validate_trusted_network_allowlist,
)
from .pairing import (
    DEFAULT_PAIRING_CODE_DIGITS,
    DEFAULT_PAIRING_MAX_ATTEMPTS,
    DEFAULT_PAIRING_TTL_SECONDS,
    PairingChallenge,
    PairingManager,
)
from .paths import SafePathResolver, resolve_safe_path, safe_resolve
from .payloads import (
    MAX_AGENT_IMAGE_BYTES,
    MAX_GENERATION_DECODED_BYTES,
    MAX_SINGLE_ASSET_BYTES,
    MAX_TEXT_CONTEXT_BYTES,
    PayloadBudgetError,
    decode_base64_payload,
    enforce_json_decoded_budget,
    enforce_text_budget,
)
from .tokens import (
    generate_session_token,
    get_process_session_token,
    rotate_process_session_token,
)

__all__ = [
    "AUTHORIZATION_HEADER",
    "AuthenticationError",
    "AuthenticationUnavailableError",
    "AuthManager",
    "BodyLimitMiddleware",
    "BodySizeLimitMiddleware",
    "DEFAULT_PAIRING_CODE_DIGITS",
    "DEFAULT_PAIRING_MAX_ATTEMPTS",
    "DEFAULT_PAIRING_TTL_SECONDS",
    "LEGACY_AUTH_HEADER",
    "MAX_AGENT_IMAGE_BYTES",
    "MAX_GENERATION_DECODED_BYTES",
    "MAX_SINGLE_ASSET_BYTES",
    "MAX_TEXT_CONTEXT_BYTES",
    "OutboundMode",
    "OutboundPolicy",
    "OutboundPolicyError",
    "OutboundResolutionError",
    "PairingAttemptsExceededError",
    "PairingChallenge",
    "PairingError",
    "PairingExpiredError",
    "PairingInvalidError",
    "PairingManager",
    "PairingReplayError",
    "PairingUnavailableError",
    "PathNotFoundSecurityError",
    "PayloadBudgetError",
    "RequestBodyError",
    "RequestBodyTooLargeError",
    "SENSITIVE_REDIRECT_HEADERS",
    "SafePathResolver",
    "SecurityError",
    "UnsafePathError",
    "ValidatedURL",
    "constant_time_token_equal",
    "decode_base64_payload",
    "enforce_json_decoded_budget",
    "enforce_text_budget",
    "generate_session_token",
    "get_process_session_token",
    "parse_bearer_token",
    "resolve_safe_path",
    "rotate_process_session_token",
    "safe_resolve",
    "same_origin",
    "strip_sensitive_headers_on_cross_origin",
    "validate_trusted_network_allowlist",
]
